# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/berlin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),berlin)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,4bef68ba2dd7125289330ba7a46c733b0da4b752)

endif
