# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/berlin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),berlin)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,6d78b055c3b6e601022d4fbf2b5174ba70a5e80b)

endif
