# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/berlin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),berlin)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,3a3f99fe9221f2905d45858500eb39ec2779742e)

endif
